
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: enterprise-db
spec:
  forProvider:
    dbInstanceClass: db.t3.medium
    engine: postgres
    allocatedStorage: 100
  providerConfigRef:
    name: aws-provider
